# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from rpcz import service
from rpcz import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rvm_pb2


_RVM = descriptor.ServiceDescriptor(
  name='RVM',
  full_name='RVM',
  file=rvm_pb2.DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=37,
  serialized_end=69,
  methods=[
  descriptor.MethodDescriptor(
    name='execute',
    full_name='RVM.execute',
    index=0,
    containing_service=None,
    input_type=rvm_pb2._QUERY,
    output_type=rvm_pb2._QUERY,
    options=None,
  ),
])

class RVM(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _RVM
class RVM_Stub(RVM):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _RVM

